/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package democrudservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Address service. Represents a row in the &quot;stud_Address&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>democrudservice.model.impl.AddressModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>democrudservice.model.impl.AddressImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Address
 * @generated
 */
@ProviderType
public interface AddressModel extends BaseModel<Address> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a address model instance should use the {@link Address} interface instead.
	 */

	/**
	 * Returns the primary key of this address.
	 *
	 * @return the primary key of this address
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this address.
	 *
	 * @param primaryKey the primary key of this address
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the address ID of this address.
	 *
	 * @return the address ID of this address
	 */
	@AutoEscape
	public String getAddressId();

	/**
	 * Sets the address ID of this address.
	 *
	 * @param addressId the address ID of this address
	 */
	public void setAddressId(String addressId);

	/**
	 * Returns the address field1 of this address.
	 *
	 * @return the address field1 of this address
	 */
	@AutoEscape
	public String getAddressField1();

	/**
	 * Sets the address field1 of this address.
	 *
	 * @param addressField1 the address field1 of this address
	 */
	public void setAddressField1(String addressField1);

	/**
	 * Returns the address field2 of this address.
	 *
	 * @return the address field2 of this address
	 */
	@AutoEscape
	public String getAddressField2();

	/**
	 * Sets the address field2 of this address.
	 *
	 * @param addressField2 the address field2 of this address
	 */
	public void setAddressField2(String addressField2);

	@Override
	public Address cloneWithOriginalValues();

}