/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eventdemo.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Data service. Represents a row in the &quot;Event_Data&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>eventdemo.model.impl.DataModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>eventdemo.model.impl.DataImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Data
 * @generated
 */
@ProviderType
public interface DataModel extends BaseModel<Data> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a data model instance should use the {@link Data} interface instead.
	 */

	/**
	 * Returns the primary key of this data.
	 *
	 * @return the primary key of this data
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this data.
	 *
	 * @param primaryKey the primary key of this data
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this data.
	 *
	 * @return the uuid of this data
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this data.
	 *
	 * @param uuid the uuid of this data
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the event ID of this data.
	 *
	 * @return the event ID of this data
	 */
	public long getEventId();

	/**
	 * Sets the event ID of this data.
	 *
	 * @param eventId the event ID of this data
	 */
	public void setEventId(long eventId);

	/**
	 * Returns the source url of this data.
	 *
	 * @return the source url of this data
	 */
	@AutoEscape
	public String getSourceURL();

	/**
	 * Sets the source url of this data.
	 *
	 * @param SourceURL the source url of this data
	 */
	public void setSourceURL(String SourceURL);

	/**
	 * Returns the host name of this data.
	 *
	 * @return the host name of this data
	 */
	@AutoEscape
	public String getHostName();

	/**
	 * Sets the host name of this data.
	 *
	 * @param hostName the host name of this data
	 */
	public void setHostName(String hostName);

	/**
	 * Returns the image of this data.
	 *
	 * @return the image of this data
	 */
	@AutoEscape
	public String getImage();

	/**
	 * Sets the image of this data.
	 *
	 * @param Image the image of this data
	 */
	public void setImage(String Image);

	/**
	 * Returns the address of this data.
	 *
	 * @return the address of this data
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this data.
	 *
	 * @param Address the address of this data
	 */
	public void setAddress(String Address);

	/**
	 * Returns the summary of this data.
	 *
	 * @return the summary of this data
	 */
	@AutoEscape
	public String getSummary();

	/**
	 * Sets the summary of this data.
	 *
	 * @param Summary the summary of this data
	 */
	public void setSummary(String Summary);

	/**
	 * Returns the total count of this data.
	 *
	 * @return the total count of this data
	 */
	@AutoEscape
	public String getTotalCount();

	/**
	 * Sets the total count of this data.
	 *
	 * @param TotalCount the total count of this data
	 */
	public void setTotalCount(String TotalCount);

	@Override
	public Data cloneWithOriginalValues();

}